### ISSUE TITLE
App main view must remain opened until dismissed by user

### ISSUE THREAD

**Issue by AmenJlili** [basshelal/Wudooh#2]
Behavior: App main view closes immediately after the user sets font face and/or size.
Expected behavior:  App main view must remain open until the user closes such view by clicking elsewhere on the page. User may choose font face or size multiple times until they settle on a choice.

**Comment by basshelal** [comment]
@jliliamen this was a problem faced while developing it, if you didn't close the popup the spacing would be too far away from each other upon a second change for some odd reason.

You are right however, even if the spacing is off the user may change multiple settings before settling on something.
I'll update it now accordingly.
Thanks

**Comment by AmenJlili** [comment]
Let me know when you have deployed changes to the chrome webstore. Thanks!

**Comment by basshelal** [comment]
@jliliamen Hi brother, the new version is live now on the [chrome store](https://chrome.google.com/webstore/detail/wudooh/nigfaloeeeakmmgndbdcijjegolpjfhn) with the fixes and changes.

Let me know how it works

**Comment by AmenJlili** [comment]
Works excellent. Thank you for your hard work!
