### ISSUE TITLE
Add support for macOS Safari

### ISSUE THREAD

**Issue by jafroni** [basshelal/Wudooh#33]
Wudooh is a great extension and I think support should be added for the Safari browser on macOS.

**Comment by basshelal** [comment]
Safari does not easily support the now defacto standard [WebExtensions API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) used by Chromium and Firefox.

In addition to that, Apple require the developer to both build the project on XCode (which means running on macOS, likely owning an Apple device) and to distribute it using their AppStore and thus be part of their closed ecosystem (which costs money regardless of your extension/app's cost, free in our case).

This is a cost too great to pay (financial and time and effort) and most developers agree, hence the smaller number of Safari extensions in comparison to Chromium or Firefox.
