### ISSUE TITLE
Finish GitHub.io static page

### ISSUE THREAD

**Issue by AmenJlili** [basshelal/Wudooh#6]
Should we consider creating a github.io page that includes proper SEO?

**Comment by basshelal** [comment]
That would be excellent! 
I have little experience in website design though so I can't help too much in that field unfortunately, I can try my best but would you be willing to help with that?

**Comment by AmenJlili** [comment]
I'm not a web dev but I will try of course.

**Comment by basshelal** [comment]
Cheers man, I'd appreciate that. 
We don't need anything too fancy really, just a static page with pictures, the logo and a description and links to both stores.
I'll see what I can do with this when I get some free time.

**Comment by basshelal** [comment]
The page is live now but I need to work on it after I'm done updating the extension with the newer features

For reference here's the Github.io page link https://basshelal.github.io/Wudooh/

**Comment by basshelal** [comment]
The site is now live and looking pretty good, I'll continue to improve it and add content but it's got everything that's needed.

**Comment by AmenJlili** [comment]
Excellent as always. Thank you for your hard work. If you are ever in the US/Canada, I would definitely love to meet you!

**Comment by basshelal** [comment]
@jliliamen Cheers man, I appreciate your kind words brother 😄
And hey if *you're* ever in the UK or Wales in particular, you're always welcome in my home 😊
Peace to you my kind friend 😊
